---
- name: this playbook install packages 
  hosts: webservers 
  become: true 

  tasks:
  - name: install package
    yum:
      #      name: ['git',  'make',  'wget', 'telnet', 'gcc', 'gzip']
      name: "{{ item }}"      
      state: installed
    
    with_items: 
        - git 
        - make
        - gcc
        - wget
        - telnet
        - gzip    
      
